app = "event-dna-platform"
primary_region = "ams"

[build]
# Queste righe possono rimanere o essere rimosse se non specifiche per il tuo Dockerfile.
# dockerfile = "Dockerfile"
# build_arg = { YOUR_BUILD_ARGS = "value" }

[processes]
  app = "python main.py" # Questo sarà il tuo unico processo principale

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = 256

# Aggiunta: Variabili d'ambiente per migliorare logging e debug
[env]
  PYTHONUNBUFFERED = "1"  # Forza output log immediato (non bufferizzato)
  LOG_LEVEL = "DEBUG"     # Imposta il livello di logging a DEBUG per output più verboso (opzionale, regola nel codice se necessario)