# fly.toml app configuration file generated for dna-nft-websocket on 2025-08-07T15:58:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dna-nft-websocket'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'
  REDIS_CHANNEL = 'blockchain_events'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256'
  cpu_kind = 'shared'
  cpus = 1
