# fly.toml app configuration file for dna-nft-websocket

app = 'dna-nft-websocket'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'
  REDIS_CHANNEL = 'blockchain_events'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1